site_name: PySNMP MIB Repository
site_description: Collection of SNMP MIB modules compatible with PySNMP
site_url: https://mibs.pysnmp.com
plugins:
  - mib_plugin
  - search
  - oid_search_plugin

extra_javascript:
  - search_index.js

extra_css:
  # Add any CSS files if needed from the asn1 directory
  # - asn1/style.css

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

markdown_extensions:
  - toc:
      permalink: true
  - meta
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
